version: "3.9"
services:
  # Контейнер для 7.4 версии PHP
  php74:
    container_name: laravel-clickhouse-lib-74
    image: laravel-clickhouse-lib-74
    build:
      context: ./
      dockerfile: ./.docker/php74/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
# Контейнер для 8.2 версии PHP
  php82:
    container_name: laravel-clickhouse-lib-82
    image: laravel-clickhouse-lib-82
    build:
      context: ./
      dockerfile: ./.docker/php82/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
# Контейнер для Laravel версии 8.3
  php83:
    container_name: laravel-clickhouse-lib-83
    image: laravel-clickhouse-lib-83
    build:
      context: ./
      dockerfile: ./.docker/php83/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php84:
    container_name: laravel-clickhouse-lib-84
    image: laravel-clickhouse-lib-84
    build:
      context: ./
      dockerfile: ./.docker/php84/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

# Контейнер  с Clickhouse
  clickhouse:
    container_name: laravel-clickhouse-clickhouse
    image: yandex/clickhouse-server:21.8-alpine
    volumes:
      - ./.docker-volume-clickhouse:/var/lib/clickhouse
      - ./.docker/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./.docker/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    healthcheck:
      test: wget --spider -q 0.0.0.0:8123/ping
      interval: 5s
      timeout: 3s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  .docker-volume-clickhouse:
    driver: local
